version: '2.4'

services:

  index_sizer:
    image: index_sizer
    build: .
    tty: true
    container_name: index_sizer

    networks:
      - elastic

    volumes:
      - ./src:/app

    # run our one-shot here :)
    command: python /app/get_size.py 2>&1
    # use this one to keep the container up and then you can debug
    #command: tail -f /dev/null

networks:
  elastic:
    driver: bridge
